#java mail sender
spring:
  mail:
    host: smtp.naver.com
    port: 587
    username: abg1418@naver.com
    password: YKHJ2EJFRXDD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true