#java mail sender
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: jihoon.kh.project@gmail.com
    password: ldczonhijgiksfpu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true